### ISSUE TITLE
Crash in 2023.2.5

### ISSUE THREAD

**Issue by gitkeerthi** [bric3/excalidraw-jetbrains-plugin#178]
IU-232.10227.8, JRE 17.0.9+7-b1000.46x64 JetBrains s.r.o., OS Mac OS X(aarch64) v14.1.1, screens 4096.0x2304.0; Retina

1. open a .excalidraw file. scribble something.
2. close.
3. crash

```
  Unhandled exception in [StandaloneCoroutine{Cancelling}@58f2c1b9, Dispatchers.Default]
  
  java.lang.AssertionError: Not alive: Lifetime `Anonymous` [Terminating, executing=0, resources=4]
at com.jetbrains.rd.util.lifetime.RLifetimeKt.assertAlive(RLifetime.kt:588)
at com.github.bric3.excalidraw.editor.ExcalidrawWebViewController.runJS(ExcalidrawWebViewController.kt:349)
at com.github.bric3.excalidraw.editor.ExcalidrawWebViewController.saveAsCoroutines(ExcalidrawWebViewController.kt:333)
at com.github.bric3.excalidraw.editor.ExcalidrawEditor$saveCoroutines$1.invokeSuspend(ExcalidrawEditor.kt:210)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelled}@58f2c1b9, Dispatchers.Default]

```

**Comment by bric3** [comment]
This may be fixed in master.
Let's fill another bug when the new version will be released.
