### ISSUE TITLE
Error on save

### ISSUE THREAD

**Issue by hyzyla** [bric3/excalidraw-jetbrains-plugin#55]
When saving drawing into PNG or SVG, nothing happens. In logs, I'm receiving an error:

```
2022-04-20 20:51:47,320 [377982618] SEVERE - #c.g.b.e.e.ExcalidrawWebViewController - [LOGSEVERITY_ERROR][https://excalidraw-jetbrains-plugin/index.html:1]:
Uncaught SyntaxError: Unexpected end of JSON input
java.lang.Throwable: [LOGSEVERITY_ERROR][https://excalidraw-jetbrains-plugin/index.html:1]:
Uncaught SyntaxError: Unexpected end of JSON input
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:182)
	at com.github.bric3.excalidraw.editor.ExcalidrawWebViewController$initJcefPanel$5.onConsoleMessage(ExcalidrawWebViewController.kt:219)
	at com.intellij.ui.jcef.JBCefClient$3.lambda$onConsoleMessage$4(JBCefClient.java:306)
	at com.intellij.ui.jcef.JBCefClient$HandlerSupport.lambda$handle$0(JBCefClient.java:725)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at java.base/java.util.Collections$SynchronizedCollection.forEach(Collections.java:2067)
	at com.intellij.ui.jcef.JBCefClient$HandlerSupport.handle(JBCefClient.java:725)
	at com.intellij.ui.jcef.JBCefClient$HandlerSupport.handleBoolean(JBCefClient.java:730)
	at com.intellij.ui.jcef.JBCefClient$3.onConsoleMessage(JBCefClient.java:305)
	at jcef/org.cef.CefClient.onConsoleMessage(CefClient.java:329)
2022-04-20 20:51:47,320 [377982618] SEVERE - #c.g.b.e.e.ExcalidrawWebViewController - PyCharm 2022.1  Build #PY-221.5080.212
2022-04-20 20:51:47,320 [377982618] SEVERE - #c.g.b.e.e.ExcalidrawWebViewController - JDK: 11.0.14.1; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
2022-04-20 20:51:47,320 [377982618] SEVERE - #c.g.b.e.e.ExcalidrawWebViewController - OS: Mac OS X
2022-04-20 20:51:47,321 [377982619] SEVERE - #c.g.b.e.e.ExcalidrawWebViewController - Plugin to blame: Excalidraw Integration version: 0.3.2
```

**Comment by bric3** [comment]
@hyzyla Is it always happening ?
Do you have a way to reproduce this ?

**Comment by hyzyla** [comment]
Seems like I cannot reproduce write now this error
