### ISSUE TITLE
The target origin provided ... does not match the recipient window's origin ('null').

### ISSUE THREAD

**Issue by bric3** [bric3/excalidraw-jetbrains-plugin#63]
Possibly happened during refactoring only

```
2022-06-26 05:15:04,454 [  14949]  ERROR - or.ExcalidrawWebViewController - [LOGSEVERITY_ERROR][about:blank:1]:
Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://excalidraw-jetbrains-plugin') does not match the recipient window's origin ('null'). 
java.lang.Throwable: [LOGSEVERITY_ERROR][about:blank:1]:
Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://excalidraw-jetbrains-plugin') does not match the recipient window's origin ('null').
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:165)
	at com.github.bric3.excalidraw.editor.ExcalidrawWebViewController$initJcefPanel$5.onConsoleMessage(ExcalidrawWebViewController.kt:222)
	at com.intellij.ui.jcef.JBCefClient$3.lambda$onConsoleMessage$4(JBCefClient.java:299)
	at com.intellij.ui.jcef.JBCefClient$HandlerSupport.lambda$handle$0(JBCefClient.java:685)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at java.base/java.util.Collections$SynchronizedCollection.forEach(Collections.java:2067)
	at com.intellij.ui.jcef.JBCefClient$HandlerSupport.handle(JBCefClient.java:685)
	at com.intellij.ui.jcef.JBCefClient$HandlerSupport.handleBoolean(JBCefClient.java:690)
	at com.intellij.ui.jcef.JBCefClient$3.onConsoleMessage(JBCefClient.java:298)
	at jcef/org.cef.CefClient.onConsoleMessage(CefClient.java:319)
```

**Comment by bric3** [comment]
development issue it seems
