### ISSUE TITLE
Unhandled NullPointerException on a CefFrame

### ISSUE THREAD

**Issue by MandySchoepASML** [bric3/excalidraw-jetbrains-plugin#82]
```
Unhandled exception in [StandaloneCoroutine{Cancelling}@4f69667d, Dispatchers.Default]

java.lang.NullPointerException: Cannot invoke "org.cef.browser.CefFrame.getURL()" because the return value of "org.cef.browser.CefBrowser.getMainFrame()" is null
	at com.github.bric3.excalidraw.editor.ExcalidrawWebViewController.runJS(ExcalidrawWebViewController.kt:352)
	at com.github.bric3.excalidraw.editor.ExcalidrawWebViewController.saveAsCoroutines(ExcalidrawWebViewController.kt:333)
	at com.github.bric3.excalidraw.editor.ExcalidrawEditor$saveCoroutines$1.invokeSuspend(ExcalidrawEditor.kt:210)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

IJ version

```
IntelliJ IDEA 2022.2.2 (Ultimate Edition)
Build #IU-222.4167.29, built on September 13, 2022
Licensed to ASML NETHERLANDS BV

Runtime version: 17.0.4+7-b469.53 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2012M
Cores: 8
Registry:
    ide.intellij.laf.enable.animation=true
    ide.balloon.shadow.size=0

Non-Bundled Plugins:
    youngstead.relative-line-numbers (1.0)
    org.intellij.plugins.hcl (222.4167.21)
    net.sjrx.intellij.plugins.systemdunitfiles (0.3.9)
    monokai-pro (1.9)
    dev.patrickpichler.darculaPitchBlackTheme (1.0.0)
    com.vermouthx.idea (1.13.3)
    com.thvardhan.gradianto (4.5)
    com.samdark.intellij-visual-studio-code-dark-plus (2.6)
    com.markskelton.one-dark-theme (5.7.0)
    com.jetbrains.darkPurpleTheme (1.3)
    com.github.bric3.excalidraw (0.3.2)
    com.arcticicestudio.nord.jetbrains (0.13.0)
    IdeaVIM (1.11.1)
    mobi.hsz.idea.gitignore (4.4.2)
    com.jetbrains.php (222.4167.37)
    org.jetbrains.plugins.phpstorm-remote-interpreter (222.4167.21)
    de.espend.idea.php.annotation (8.2.3)
    com.mesour.intellij.neon (1.0.4)
    com.kalessil.phpStorm.phpInspectionsEA (4.0.7.1)
    com.intellij.php.tools.quality.phpstan (222.4167.35)
    org.jetbrains.plugins.phpstorm-docker (222.4167.21)
    com.intellij.kubernetes (222.4167.21)
    Pythonid (222.4167.37)
    ru.adelf.idea.dotenv (2022.2)
    MetricsReloaded (1.12)

Kotlin: 222-1.7.10-release-334-IJ4167.29
```

**Comment by MandySchoepASML** [comment]
```
java.lang.Throwable: [LOGSEVERITY_ERROR][https://excalidraw-jetbrains-plugin/index.html:12174]:
[object DOMException]
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:184)
	at com.github.bric3.excalidraw.editor.ExcalidrawWebViewController$initJcefPanel$5.onConsoleMessage(ExcalidrawWebViewController.kt:219)
	at com.intellij.ui.jcef.JBCefClient$3.lambda$onConsoleMessage$4(JBCefClient.java:306)
	at com.intellij.ui.jcef.JBCefClient$HandlerSupport.lambda$handle$0(JBCefClient.java:725)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at java.base/java.util.Collections$SynchronizedCollection.forEach(Collections.java:2131)
	at com.intellij.ui.jcef.JBCefClient$HandlerSupport.handle(JBCefClient.java:725)
	at com.intellij.ui.jcef.JBCefClient$HandlerSupport.handleBoolean(JBCefClient.java:730)
	at com.intellij.ui.jcef.JBCefClient$3.onConsoleMessage(JBCefClient.java:305)
	at jcef/org.cef.CefClient.onConsoleMessage(CefClient.java:370)
```

I also got this error and it might be related to it.

I am running IntelliJ in a really strict environment, with Cisco Umbrella, meaning that it could be related to using an (according to IntelliJ) unsigned certificate perhaps when doing HTTP calls?

**Comment by bric3** [comment]
I believe this a different issue, maybe open a new issue.
This one indicate something that happened within the browser. It's very very hard to debug, even locally.

> I am running IntelliJ in a really strict environment, with Cisco Umbrella, meaning that it could be related to using an (according to IntelliJ) unsigned certificate perhaps when doing HTTP calls?

I don't think certificate should have anything as there is a specific mechanism to handle `https://excalidraw-jetbrains-plugin`.

Does intellij actually tell you it's an unsigned certificate issue ?

Also not sure how to fix this.

**Comment by abentele** [comment]
I have the same issue, see my duplicate: #141

**Comment by abentele** [comment]
yes, sure.

I use IntelliJ IDEA 2023.1 (Ultimate Edition) ("Build #IU-231.8109.175, built on March 28, 2023")
Runtime version: 17.0.6+10-b829.5 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.

Excalidraw Integration 0.3.2


Steps to reproduce:
* Open IntelliJ
* Disable Excalidraw plugin
* Close and re-open IntelliJ
* in the Project Explorer: right click and select New > File
* type in the file name "test.excalidraw"
* open this file in the editor
* The editor shows in its header: "Plugins supporting *.excalidraw files found" with the option to "Enable plugin" => click on "Enable plugin"
* the editor switches into a state with tabs "Text" and "Excalidraw" in the bottom line.

In the notifications of IntelliJ the exception mentioned in this issue is logged:
```
java.lang.NullPointerException: Cannot invoke "org.cef.browser.CefFrame.getURL()" because the return value of "org.cef.browser.CefBrowser.getMainFrame()" is null
...
```

If I now switch to the "Excalidraw" tab, this exception is logged:
```
java.lang.Throwable: [LOGSEVERITY_ERROR][https://excalidraw-jetbrains-plugin/index.html:1]:
Uncaught SyntaxError: Unexpected end of JSON input
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:202)
	at com.github.bric3.excalidraw.editor.ExcalidrawWebViewController$initJcefPanel$5.onConsoleMessage(ExcalidrawWebViewController.kt:219)
	at com.intellij.ui.jcef.JBCefClient$3.lambda$onConsoleMessage$4(JBCefClient.java:305)
	at com.intellij.ui.jcef.JBCefClient$HandlerSupport.lambda$handle$0(JBCefClient.java:726)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at java.base/java.util.Collections$SynchronizedCollection.forEach(Collections.java:2131)
	at com.intellij.ui.jcef.JBCefClient$HandlerSupport.handle(JBCefClient.java:726)
	at com.intellij.ui.jcef.JBCefClient$HandlerSupport.handleBoolean(JBCefClient.java:731)
	at com.intellij.ui.jcef.JBCefClient$3.onConsoleMessage(JBCefClient.java:304)
	at jcef/org.cef.CefClient.onConsoleMessage(CefClient.java:352)
```

**Comment by bric3** [comment]
I believe this issue to be closed on master. If it happen again on the version let's open a new issue.
